### ISSUE TITLE
[BUG] Recent update broke stagers generation and teamserver

### ISSUE THREAD

**Issue by hackabean** [byt3bl33d3r/SILENTTRINITY#111]
@byt3bl33d3r 
Steps to reproduce:
Git clone https://github.com/byt3bl33d3r/SILENTTRINITY.git

Run teamserver and ST, set up the stager, error:

Details:
![image](https://user-images.githubusercontent.com/50614334/65966944-58369700-e450-11e9-848a-59ed798ce399.png)

After that teamserver will be unable to launch.
Error from teamserver:

> 

2019-10-01 14:37:06,602 12945 IPCServer - [DEBUG] ipcserver.py: run - Started IPC server on 127.0.0.1:63544
2019-10-01 14:37:06,823 12945 MainThread - [DEBUG] ipcserver.py: attach - Attaching event: GET_LISTENERS -> Listeners._get_listeners
2019-10-01 14:37:07,221 12945 MainThread - [ERROR] loader.py: get_loadables - Failed loading listener core/teamserver/listeners/wmi.py: No module named 'impacket'
2019-10-01 14:37:07,221 12945 MainThread - [DEBUG] loader.py: get_loadables - Loaded 2 listener(s)
2019-10-01 14:37:07,221 12945 MainThread - [DEBUG] ipcserver.py: attach - Attaching event: KEY_EXCHANGE -> Sessions.kex
2019-10-01 14:37:07,221 12945 MainThread - [DEBUG] ipcserver.py: attach - Attaching event: ENCRYPT_STAGE -> Sessions.gen_encrypted_stage
2019-10-01 14:37:07,221 12945 MainThread - [DEBUG] ipcserver.py: attach - Attaching event: SESSION_STAGED -> Sessions.notify_session_staged
2019-10-01 14:37:07,221 12945 MainThread - [DEBUG] ipcserver.py: attach - Attaching event: SESSION_REGISTER -> Sessions._register
2019-10-01 14:37:07,221 12945 MainThread - [DEBUG] ipcserver.py: attach - Attaching event: SESSION_CHECKIN -> Sessions.session_checked_in
2019-10-01 14:37:07,221 12945 MainThread - [DEBUG] ipcserver.py: attach - Attaching event: NEW_JOB -> Sessions.add_job
2019-10-01 14:37:07,221 12945 MainThread - [DEBUG] ipcserver.py: attach - Attaching event: JOB_RESULT -> Sessions.job_result
Traceback (most recent call last):
  File "teamserver.py", line 195, in <module>
    loop.run_until_complete(server(stop))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "teamserver.py", line 147, in server
    ts = TeamServer()
  File "teamserver.py", line 44, in __init__
    'sessions': Sessions(self),
  File "/home/user/ST/SILENTTRINITY/core/teamserver/contexts/sessions.py", line 47, in __init__
    self._register(guid, psk)
  File "/home/user/ST/SILENTTRINITY/core/teamserver/contexts/sessions.py", line 71, in _register
    db.add_session(guid, psk)
  File "/home/user/ST/SILENTTRINITY/core/teamserver/db.py", line 56, in add_session
    self.db.execute("INSERT INTO sessions (guid, psk) VALUES (?,?)", [str(guid), psk])
sqlite3.IntegrityError: UNIQUE constraint failed: sessions.guid, sessions.psk

**Comment by mlgualtieri** [comment]
Can confirm same issue.  Backing out to commit 244b974a1f7048620eda54dbdb75b4f5f334a894 is a workaround for the time being.

**Comment by byt3bl33d3r** [comment]
Wow y'all are stalkers :P, gimme a sec pushing a fix now.

**Comment by byt3bl33d3r** [comment]
Fixed! My bad. Gonna write some tests for this.
Cheers

**Comment by mlgualtieri** [comment]
Works for me, thanks!
