### ISSUE TITLE
[BUG] Deleted logs folder handling

### ISSUE THREAD

**Issue by leitosama** [byt3bl33d3r/SILENTTRINITY#118]
# Getting errors with deleted logs dir

## Context
SILENTTRINITY can't handling deleted logs directory error.

* SILENTTRINITY Version: 0.4.5dev
* OS running the TeamServer: Parrot OS 
* Python version running the Teamserver: 3.7.4+

## Current Behavior

Teamserver cannot write logs and dont want do create stagers.

### Steps to Reproduce

1. Delete a logs folder
2. Try to generate stager

### Failure Logs
```
2019-10-17 16:08:46,526 5422 MainThread - [DEBUG] teamserver.py: process_client_message - Received message from ch1n4@127.0.0.1 path:/ msg: {'id': '36vqAKRkek', 'ctx': 'stagers', 'cmd': 'generate', 'args': {'listener_name': 'kek'}, 'data': {}}
Traceback (most recent call last):
  File "teamserver.py", line 64, in process_client_message
    result = cmd_handler(**message['args'])
  File "/opt/SILENTTRINITY/core/teamserver/contexts/stagers.py", line 62, in generate
    self.teamserver.contexts['sessions']._register(guid, psk)
  File "/opt/SILENTTRINITY/core/teamserver/contexts/sessions.py", line 68, in _register
    session = Session(guid, psk)
  File "/opt/SILENTTRINITY/core/teamserver/session.py", line 30, in __init__
    os.mkdir(f"./data/logs/{self._guid}")
```

**Comment by byt3bl33d3r** [comment]
It should check this folder exists every time you start the teamserver as per https://github.com/byt3bl33d3r/SILENTTRINITY/blob/master/silenttrinity/core/teamserver/__main__.py#L185-L189

When/How did you delete the logs folder?
