### ISSUE TITLE
Output of modules not displayed on the cli client 

### ISSUE THREAD

**Issue by zqyves** [byt3bl33d3r/SILENTTRINITY#128]
Hi there, 

I am using the latest github version on Ubuntu 19.04. 

The output of the modules executed on the agent is not displayed on the cli client. The is true for all modules and I also "think" some other functionality. I have done some debugging and figured this is caused in <ST_HOME>/silenttrinity/core/teamserver/users.py line 17
```
  async def send(self, data):
        await self.websocket.send(json.dumps(data))
```
I changed this to 
```
   async def send(self, data):
        print(data)
        await self.websocket.send(json.dumps(data))
```
and the output I got is the below
```
019-10-23 07:12:21,864 59140 Thread-2 - [DEBUG] sessions.py: job_result - 2f1a51f1-8dbb-4ed7-9238-27536401c323 returned job/command result (id: d4mfigfcnZ)
{'type': 'event', 'name': <Events.JOB_RESULT: 12>, 'data': {'id': 'd4mfigfcnZ', 'output': 'MSEDGEWIN10\\IEUser\r\n', 'session': '2f1a51f1-8dbb-4ed7-9238-27536401c323', 'address': '10.254.254.137'}}
2019-10-23 07:12:21,865 59140 MainThread - [ERROR] base_events.py: default_exception_handler - Task exception was never retrieved
future: <Task finished coro=<User.send() done, defined at /home/zacharias/tools/SILENTTRINITY/silenttrinity/core/teamserver/users.py:16> exception=TypeError('Object of type Events is not JSON serializable')>
Traceback (most recent call last):
  File "/home/zacharias/tools/SILENTTRINITY/silenttrinity/core/teamserver/users.py", line 18, in send
    await self.websocket.send(json.dumps(data))
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Events is not JSON serializable
2019-10-23 07:12:21,867 60380 MainThread - [DEBUG] ipcclient.py: dispatch_event - Received data back from event: Events.JOB_RESULT - OK
```
so for some reason the teamserver cant deserialise and transform the results so it can send them to the cli. 

That is as far as I could take it. 

Kind regards,

**Comment by byt3bl33d3r** [comment]
Fixed! Thanks. My bad!

**Comment by zqyves** [comment]
Hey, 

thanks for that - updated and it works like a charm.

don't know how often it is said - or if it said for that matter - but thanks a lot for putting the effort and time to create this. 

Enjoy WWHackinFest!
