### ISSUE TITLE
[BUG] 'PromptSession' object has no attribute 'prompt_async'

### ISSUE THREAD

**Issue by dgbuser** [byt3bl33d3r/SILENTTRINITY#146]
Ubuntu: Eoan
Python: 3.7.5
ST Version  : 0.4.6dev

Teamserver CMD: python ./st.py teamserver 10.0.0.1 password
Client CMD: python ./st.py client wss://test:password@10.0.0.1:5000

Error:
Traceback (most recent call last):
  File "./st.py", line 6, in <module>
    run()
  File "/SILENTTRINITY/silenttrinity/__main__.py", line 19, in run
    client.start(docopt(client.__doc__, argv=args["<args>"]))
  File "/SILENTTRINITY/silenttrinity/core/client/__main__.py", line 30, in start
    asyncio.run(main(args))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/SILENTTRINITY/silenttrinity/core/client/__main__.py", line 24, in main
    await s.cmdloop()
  File "/SILENTTRINITY/silenttrinity/core/client/cmdloop.py", line 276, in cmdloop
    text = await self.prompt_session.prompt_async()

AttributeError: 'PromptSession' object has no attribute 'prompt_async'

**Comment by daddycocoaman** [comment]
Can you verify that your version of prompt_toolkit is >=3.0.0?

**Comment by dgbuser** [comment]
Like requirements.txt prompt_toolkit=3.0.2. Try dist binary, prompt_toolkit=3.0.3 & prompt_toolkit=3.0.5 via pip, same error.

seem like this is just error in the way ST is called and, the docs need to update.

Doc:
Teamserver CMD: python st teamserver 10.0.0.1 password
Client CMD: python st client wss://test:password@10.0.0.1:5000

Attempted:
Teamserver CMD: python ./st.py teamserver 10.0.0.1 password
Client CMD: python ./st.py client wss://test:password@10.0.0.1:5000

Working:
Teamserver CMD: bin/st teamserver 10.0.0.1 password
Client CMD: bin/st client wss://test:password@10.0.0.1:5000

**Comment by w1ld3r** [comment]
I was getting this error and `pip3 install prompt_toolkit==3.0.8` resolve my issue.
