### ISSUE TITLE
Boo casting exception when executing modules

### ISSUE THREAD

**Issue by fabamatic** [byt3bl33d3r/SILENTTRINITY#153]
## Context
Not sure if this is a bug, may be something wrong on my side, but I searched for help online but couldn't find anything.
Using default stagers and modules when I try to execute any module on victim I get Boo casting exception:
System.InvalidCastException: Unable to cast object of type 'Boo.Lang.Parser.BooParsingStep' to type 'Boo.Lang.Compiler.ICompilerStep'

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* SILENTTRINITY Version: 0.4.6dev
* OS running the Client: Kali 5.4.0
* Python Version Running the Client 3.83
* OS running the TeamServer: Kali 5.4.0
* Python version running the Teamserver: 3.8.3

## Current Behavior
When module is run I get this error stack:
`[1] ST (modules)(boo/msgbox) ≫ run cb939822-4cc2-4958-99b5-cd02ba46d4eb
[*] [TS-6GaU9] cb939822-4cc2-4958-99b5-cd02ba46d4eb returned job result (id: EsBHWMws62)
System.InvalidCastException: Unable to cast object of type 'Boo.Lang.Parser.BooParsingStep' to type 'Boo.Lang.Compiler.ICompilerStep'.
   at Boo.Lang.Compiler.Steps.Parsing.NewParserStep()
   at Boo.Lang.Compiler.Steps.Parsing.get_Parser()
   at Boo.Lang.Compiler.Steps.Parsing.Initialize(CompilerContext context)
   at Boo.Lang.Compiler.CompilerPipeline.RunStep(CompilerContext context, ICompilerStep step)
   at Boo.Lang.Compiler.CompilerPipeline.RunSteps(CompilerContext context)
   at Boo.Lang.Compiler.CompilerPipeline.<Run>c__AnonStorey0.<>m__0()
   at Boo.Lang.Environments.ActiveEnvironment.With(IEnvironment environment, Procedure code)
   at Boo.Lang.Compiler.BooCompiler.Run(CompileUnit compileUnit)
   at Boo.Lang.Compiler.BooCompiler.Run()
   at STJob.CompileAndRun(String source, List references) in C:\Users\user\Downloads\Stage.boo:line 526
   at STJob.Start() in C:\Users\user\Downloads\Stage.boo:line 386
`

Any help is appreciated!

**Comment by fabamatic** [comment]
Some misc info, doesn't matetr which stager/listener I am using, looks like the problem is in one of the .boo files?

**Comment by fabamatic** [comment]
Problem is related to this issue:
https://github.com/byt3bl33d3r/Naga/issues/3#issue-603551977

**Comment by a6n1** [comment]
Any solutions for this one? This also occurred on my end as well.

**Comment by fabamatic** [comment]
> Any solutions for this one? This also occurred on my end as well.

Yes I used the fork that d-sec created https://github.com/d-sec-net/SILENTTRINITY. Fixes all issues.

**Comment by a6n1** [comment]
i tried using @d-sec-net 's fork but when I started st.py teamserver, this error showed up:

2020-08-26 01:23:58,984 5252 MainThread - [ERROR] loader.py: get_loadables - Failed loading module /opt/SILENTTRINITY/silenttrinity/core/teamserver/modules/boo/upload.py: module 'module' has no attribute 'STModule'
