### ISSUE TITLE
[BUG] Not able to run st.py

### ISSUE THREAD

**Issue by fried213** [byt3bl33d3r/SILENTTRINITY#158]
## Context

This is my first time running silent trinity

* SILENTTRINITY Version: 
* OS running the Client: ubuntu server 18.04.5
* Python Version Running the Client 3.7
* OS running the TeamServer: ubuntu server 18.04.5
* Python version running the Teamserver:

## Expected Behavior

should be able to run st.py teamserver

## Current Behavior

it fails and doesn't run with error message below

## Failure Information

Note that I've never gotten it to work. This is my first time running the tool

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. run "sudo python3 st.py teamserver 127.0.0.1 cpassword"
   ...

### Failure Logs

~/SILENTTRINITY$ sudo python3 st.py teamserver 127.0.0.1 password
2020-10-14 14:00:47,131 8896 IPCServer - [DEBUG] ipcserver.py: run - Started IPC server on 127.0.0.1:60026
2020-10-14 14:00:47,229 8896 MainThread - [DEBUG] selector_events.py: __init__ - Using selector: EpollSelector
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "st.py/__main__.py", line 3, in <module>
  File "st.py/_bootstrap/__init__.py", line 233, in bootstrap
  File "st.py/_bootstrap/__init__.py", line 36, in run
  File "/home/azureuser/.shiv/st_e08a189f912c98d510f2295214eb69376b58a5fda84586b27d39aae149f46a38/site-packages/silenttrinity/__main__.py", line 22, in run
    teamserver.start(docopt(teamserver.__doc__, argv=args["<args>"]))
  File "/home/azureuser/.shiv/st_e08a189f912c98d510f2295214eb69376b58a5fda84586b27d39aae149f46a38/site-packages/silenttrinity/core/teamserver/__main__.py", line 201, in start
    loop.run_until_complete(server(stop, args, teamserver_digest))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/azureuser/.shiv/st_e08a189f912c98d510f2295214eb69376b58a5fda84586b27d39aae149f46a38/site-packages/silenttrinity/core/teamserver/__main__.py", line 148, in server
    ts = TeamServer()
  File "/home/azureuser/.shiv/st_e08a189f912c98d510f2295214eb69376b58a5fda84586b27d39aae149f46a38/site-packages/silenttrinity/core/teamserver/__main__.py", line 40, in __init__
    self.loop = asyncio.get_running_loop()
AttributeError: module 'asyncio' has no attribute 'get_running_loop'

**Comment by byt3bl33d3r** [comment]
@fried213 You're either running an old Python version or your Python install is broken.
