### ISSUE TITLE
Got error while using boo/inject

### ISSUE THREAD

**Issue by 25-do** [byt3bl33d3r/SILENTTRINITY#174]
[1] ST (modules)(boo/inject) ≫ run 06cbf024-e2af-4de6-9c00-9d3a535932e0
?[34m[*]?[0m [TS-ouRL4] 06cbf024-e2af-4de6-9c00-9d3a535932e0 returned job result (id: VFhJqJiqjK)
System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.IO.StringReader..ctor(String s)
   at Boo.Lang.Compiler.IO.StringInput..ctor(String name, String contents)
   at STJob.CompileAndRun(String source, List references) in C:\Users\DELL\Downloads\script.boo:line 513
   at STJob.Start() in C:\Users\DELL\Downloads\script.boo:line 390

**Comment by chintemur** [comment]
Hi

**Comment by chintemur** [comment]
Pronouns

**Comment by 25-do** [comment]
Hello
